version: "3.9"

services:
  as-telegram-bot:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data
    restart: unless-stopped

volumes:
  db_data: