version: "3.9"

services:
  as-telegram-bot:
    build: .
    env_file:
      - .env.docker
    depends_on:
      - db
    command: >
      sh -c "
        alembic upgrade head &&
        python app/main.py
      "
    restart: unless-stopped


  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data: