[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "telegram-bot"
version = "0.1.0"
description = "A simple Telegram bot using aiogram"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "aiogram>=3.0.0",
]

[tool.uv]
python = "3.11"
