[project]
name = "telegram-bot"
version = "0.1.0"
description = "A simple Telegram bot using aiogram"
requires-python = ">=3.12"

dependencies = [
    "aiogram>=3.0.0",
    "sqlalchemy>=2.0.0",
    "asyncpg>=0.29.0",
    "alembic>=1.16.4",
    "python-dotenv>=1.0.0"
]

