"""add photo field to car

Revision ID: 3d5040d0806f
Revises: fa90f39ede33
Create Date: 2025-09-30 17:22:06.296590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5040d0806f'
down_revision: Union[str, Sequence[str], None] = 'fa90f39ede33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('photo_file_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'photo_file_id')
    # ### end Alembic commands ###
